### ISSUE TITLE
Memory savings?

### ISSUE THREAD

**Issue by jlamprou** [dingo-actual/infini-transformer#12]
Great implementation! I have a couple of questions:
Does you implementation have O(N) complexity like the papers? What kind of memory savings should i expect compared classic sdpa attention? It would be great if you can give me some numbers on the VRAM usage during your training test compared to classic SDPA.
Thanks!

**Comment by dingo-actual** [comment]
The implementation of `CompressiveMemory` has a memory complexity of $O(S^2)$ where $S$ is the segment length. Each recurrent step uses a constant-sized memory matrix and a constant-sized normalization vector, along with full attention over the $S$ tokens in the current segment from the full sequence.

As for measured VRAM usage, I only have the compute to handle very small models. Any measurements I take would be meaningless. If I can find a sponsor, I'd be happy to report a full ablation comparing architectures that use `InfiniFormer`, `MoDInfiniFormer` and vanilla transformers. Until that time, I can only provide memory complexity based on analysis of the code.

Going to close this for now, but if I find a sponsor, I'll reopen and work on ablations.

**Comment by jlamprou** [comment]
@dingo-actual The paper clearly states that the whole point is to avoid quadratic complexity O(S^2). So what's the point of using this? I think you should rethink you approach, I'm pretty sure you are supposed to segment a sequence before passing it to the model like other works cited by the paper (Transformers-XL, Memformers etc) and not segment inside the attention . Take a look at the architecture from the paper:
![Screenshot_20240424-152617_Brave](https://github.com/dingo-actual/infini-transformer/assets/41962910/79ad29b8-57e5-40a8-b711-49b06c114592)
