### ISSUE TITLE
Add comments to the example script

### ISSUE THREAD

**Issue by dingo-actual** [dingo-actual/infini-transformer#14]
The example script isn't complicated, but it should have comments all the same.

**Comment by willtai** [comment]
Is this taken? I can add some docstrings and comments

**Comment by dingo-actual** [comment]
You're welcome to it. I'll go ahead and assign it to you. Thanks for the help!

**Comment by willtai** [comment]
https://github.com/dingo-actual/infini-transformer/pull/17 Opened a PR here

**Comment by willtai** [comment]
I think we can close this now after https://github.com/dingo-actual/infini-transformer/pull/18
