### ISSUE TITLE
Causal Masking.

### ISSUE THREAD

**Issue by vmarinowski** [dingo-actual/infini-transformer#4]
Exactly where to use causal masking?

**Comment by dingo-actual** [comment]
I'm working on adding that now 😄

**Comment by dingo-actual** [comment]
Just added. Just be aware the masking isn't fully "causal" being the compressive memory updates allow tokens within a segment to attend to future tokens within that same segment. Without changing the compressive memory formulation, it's not something I can get around.

**Comment by GaoXinJian-USTC** [comment]
> Just added. Just be aware the masking isn't fully "causal" being the compressive memory updates allow tokens within a segment to attend to future tokens within that same segment. Without changing the compressive memory formulation, it's not something I can get around.

If  just use the fully causal self-attention without the compressive memory , would there be a significant decrease?
